{% set version = "2023.0.1" %}

package:
  name: lsprotocol
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/l/lsprotocol/lsprotocol-{{ version }}.tar.gz
    sha256: cc5c15130d2403c18b734304339e51242d3018a05c4f7d0f198ad6e0cd21861d
  - folder: src
    url: https://github.com/microsoft/lsprotocol/archive/refs/tags/{{ version }}.tar.gz
    sha256: 0697ef66ca1b547cadb4c27080d6095c2e403b9aeb05401de383126a70720a56

build:
  number: 1
  noarch: python
  script:
    - cd dist 
    - {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps --disable-pip-version-check

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python {{ python_min }}
  run:
    - attrs >=21.3.0
    - cattrs !=23.2.1
    - python >={{ python_min }}

test:
  source_files:
    - src/conftest.py
    - src/tests
    - src/generator
  imports:
    - lsprotocol
  commands:
    - pip check
    - cd src
    - coverage run --source=lsprotocol --branch pytest -vv --tb=long --color-yes
    - coverage report --show-missing --skip-covered --fail-under=88
  requires:
    - pyhamcrest
    - importlib_resources
    - jsonschema
    - pip
    - pytest-cov
    - python {{ python_min }}

about:
  home: https://pypi.org/project/lsprotocol
  summary: Python implementation of the Language Server Protocol.
  dev_url: https://github.com/microsoft/lsprotocol
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
