{% set version = "2023.0.0a0" %}

package:
  name: lsprotocol
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/l/lsprotocol/lsprotocol-{{ version }}.tar.gz
    sha256: 3cb82ea9fd11a4df5eaebb58cc6800a4b2c03eada601ad6056d0b65601c66374
  - folder: src
    url: https://github.com/microsoft/lsprotocol/archive/refs/tags/{{ version }}.tar.gz
    sha256: 5a29ca7e48b7302e37120d9e68fe282652650429abbe1f094adca6f93ec2495f

build:
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.7
  run:
    - attrs
    - cattrs
    - python >=3.7

test:
  source_files:
    - src/tests
    - src/generator
  imports:
    - lsprotocol
  commands:
    - pip check
    - cd src/tests && pytest -vv --cov=lsprotocol --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=94
  requires:
    - pyhamcrest
    - importlib_resources
    - jsonschema
    - pip
    - pytest-cov

about:
  home: https://pypi.org/project/lsprotocol
  summary: Python implementation of the Language Server Protocol.
  dev_url: https://github.com/microsoft/lsprotocol
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
