{% set version = "2023.0.0a1" %}

package:
  name: lsprotocol
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/l/lsprotocol/lsprotocol-{{ version }}.tar.gz
    sha256: 32edfd4856abba1349bf5a070567445b3d7286951afba3644b472629796f82d0
  - folder: src
    url: https://github.com/microsoft/lsprotocol/archive/refs/tags/{{ version }}.tar.gz
    sha256: 495e004c38c4f5986c59b1241c478e76e0c79107005e276879e1f34c60e3b5bd

build:
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.7
  run:
    - attrs
    - cattrs
    - python >=3.7

test:
  source_files:
    - src/conftest.py
    - src/tests
    - src/generator
  imports:
    - lsprotocol
  commands:
    - pip check
    - cd src && pytest ./tests -vv --cov=lsprotocol --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=94
  requires:
    - pyhamcrest
    - importlib_resources
    - jsonschema
    - pip
    - pytest-cov

about:
  home: https://pypi.org/project/lsprotocol
  summary: Python implementation of the Language Server Protocol.
  dev_url: https://github.com/microsoft/lsprotocol
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
